-- Cleanup physical_assessments by removing health-related columns (if they were added)
-- and ensuring it focuses strictly on posture and images.

ALTER TABLE public.physical_assessments
DROP COLUMN IF EXISTS gender,
DROP COLUMN IF EXISTS height,
DROP COLUMN IF EXISTS weight,
DROP COLUMN IF EXISTS age,
DROP COLUMN IF EXISTS body_fat,
DROP COLUMN IF EXISTS experience,
DROP COLUMN IF EXISTS wake_time,
DROP COLUMN IF EXISTS sleep_time,
DROP COLUMN IF EXISTS train_time,
DROP COLUMN IF EXISTS allergies,
DROP COLUMN IF EXISTS favorite_foods,
DROP COLUMN IF EXISTS weight_strategy,
DROP COLUMN IF EXISTS daily_activity,
DROP COLUMN IF EXISTS measurement_shoulder,
DROP COLUMN IF EXISTS measurement_chest,
DROP COLUMN IF EXISTS measurement_bicep_left,
DROP COLUMN IF EXISTS measurement_bicep_right,
DROP COLUMN IF EXISTS measurement_waist,
DROP COLUMN IF EXISTS measurement_hip,
DROP COLUMN IF EXISTS measurement_thigh_left,
DROP COLUMN IF EXISTS measurement_thigh_right,
DROP COLUMN IF EXISTS measurement_calf_left,
DROP COLUMN IF EXISTS measurement_calf_right,
DROP COLUMN IF EXISTS medical_cardiovascular,
DROP COLUMN IF EXISTS medical_blood_pressure,
DROP COLUMN IF EXISTS medical_diabetes,
DROP COLUMN IF EXISTS medical_asthma,
DROP COLUMN IF EXISTS medical_vestibular,
DROP COLUMN IF EXISTS medical_back_issue,
DROP COLUMN IF EXISTS medical_stomach,
DROP COLUMN IF EXISTS medical_nerves,
DROP COLUMN IF EXISTS medical_neck_shoulder_pain,
DROP COLUMN IF EXISTS sleep_hours,
DROP COLUMN IF EXISTS medical_sciatica,
DROP COLUMN IF EXISTS medical_joints,
DROP COLUMN IF EXISTS is_smoker,
DROP COLUMN IF EXISTS is_alcoholic,
DROP COLUMN IF EXISTS medical_hernia,
DROP COLUMN IF EXISTS medical_surgery,
DROP COLUMN IF EXISTS medical_insomnia,
DROP COLUMN IF EXISTS medical_hip_alignment;
