-- Extend physical_assessments table with detailed health and measurement fields
ALTER TABLE public.physical_assessments
ADD COLUMN IF NOT EXISTS gender TEXT,
ADD COLUMN IF NOT EXISTS height DECIMAL,
ADD COLUMN IF NOT EXISTS weight DECIMAL,
ADD COLUMN IF NOT EXISTS age INTEGER,
ADD COLUMN IF NOT EXISTS body_fat DECIMAL,
ADD COLUMN IF NOT EXISTS experience BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS wake_time TIME,
ADD COLUMN IF NOT EXISTS sleep_time TIME,
ADD COLUMN IF NOT EXISTS train_time TIME,
ADD COLUMN IF NOT EXISTS allergies TEXT,
ADD COLUMN IF NOT EXISTS favorite_foods TEXT,
ADD COLUMN IF NOT EXISTS weight_strategy TEXT,
ADD COLUMN IF NOT EXISTS daily_activity TEXT,

-- Measurements
ADD COLUMN IF NOT EXISTS measurement_shoulder DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_chest DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_bicep_left DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_bicep_right DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_waist DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_hip DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_thigh_left DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_thigh_right DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_calf_left DECIMAL,
ADD COLUMN IF NOT EXISTS measurement_calf_right DECIMAL,

-- Medical Conditions
ADD COLUMN IF NOT EXISTS medical_cardiovascular TEXT,
ADD COLUMN IF NOT EXISTS medical_blood_pressure TEXT,
ADD COLUMN IF NOT EXISTS medical_diabetes TEXT,
ADD COLUMN IF NOT EXISTS medical_asthma TEXT,
ADD COLUMN IF NOT EXISTS medical_vestibular TEXT,
ADD COLUMN IF NOT EXISTS medical_back_issue TEXT,
ADD COLUMN IF NOT EXISTS medical_stomach TEXT,
ADD COLUMN IF NOT EXISTS medical_nerves TEXT,
ADD COLUMN IF NOT EXISTS medical_neck_shoulder_pain TEXT,
ADD COLUMN IF NOT EXISTS sleep_hours DECIMAL,
ADD COLUMN IF NOT EXISTS medical_sciatica TEXT,
ADD COLUMN IF NOT EXISTS medical_joints TEXT,
ADD COLUMN IF NOT EXISTS is_smoker BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_alcoholic BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS medical_hernia TEXT,
ADD COLUMN IF NOT EXISTS medical_surgery TEXT,
ADD COLUMN IF NOT EXISTS medical_insomnia TEXT,
ADD COLUMN IF NOT EXISTS medical_hip_alignment TEXT;
